  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="icon" type="image/png" href="images/fav.png">
    <link rel="apple-touch-icon" href="images/fav.png">

    <link rel="dns-prefetch" href="#">
    <link rel="preconnect" href="#" crossorigin />
    <link rel="preconnect" href="https://cdn.jsdelivr.net">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="preconnect" href="https://www.gstatic.com">
    <link rel="preconnect" href="https://www.googletagmanager.com">
    <link rel="preconnect" href="https://www.recaptcha.net">


    <link rel="preload" href="css/main.css?id=7f87c774bb3c7e6f4a962ffd80a44d3a" as="style">
    <link rel="preload" as="image" href="images/btn-burger.png?id=b29d034c28400fda231152345632cd48">
    <!--<link rel="preload" href="json/intro.json" as="fetch" crossorigin>-->
    <link rel="stylesheet" href="css/main.css?id=7f87c774bb3c7e6f4a962ffd80a44d3a">
    <link href="https://fonts.googleapis.com/css2?family=Oxygen:wght@300;400;700&display=swap" rel="stylesheet">
    
    <?php if (isset($_GET['admin_preview']) && $_GET['admin_preview'] == 1): ?>
        <!-- Admin Preview Helper -->
        <script src="admin/assets/js/admin-preview.js" defer></script>
    <?php endif; ?>
<style>
        @media (max-width: 768px) {
            .hide-on-mobile {
                display: none;
            }
			.show-on-mobile {
                display: block;
            }
        }
</style>
<style>
[x-cloak] { display: none !important; }
</style>
	<style>
/* Default styling for larger screens */
.responsive-svg {
  width: 50vw; /* 50% of the viewport width */
  height: auto; /* Maintain aspect ratio */
  max-height: 500px; /* Limit the height */
}

/* Make it larger for smaller devices */
@media (max-width: 768px) {
  .responsive-svg {
    width: 80vw; /* 80% of the viewport width for tablets and smaller screens */
    max-height: 400px; /* Adjust max height */
  }
}

/* For very small screens like mobile phones */
@media (max-width: 480px) {
  .responsive-svg {
    width: 90vw; /* 90% of the viewport width for phones */
    max-height: 300px; /* Reduce height for small devices */
  }
}
</style>
<style>
/***************************************************
 * Generated by SVG Artista on 1/22/2025, 11:59:41 AM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/

@-webkit-keyframes animate-svg-fill-1 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(0, 0, 0);
  }
}

@keyframes animate-svg-fill-1 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(0, 0, 0);
  }
}

.svg-elem-1 {
  -webkit-animation: animate-svg-fill-1 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8s both;
          animation: animate-svg-fill-1 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8s both;
}

@-webkit-keyframes animate-svg-fill-2 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-2 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-2 {
  -webkit-animation: animate-svg-fill-2 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.81s both;
          animation: animate-svg-fill-2 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.81s both;
}

@-webkit-keyframes animate-svg-fill-3 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-3 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-3 {
  -webkit-animation: animate-svg-fill-3 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8200000000000001s both;
          animation: animate-svg-fill-3 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8200000000000001s both;
}

@-webkit-keyframes animate-svg-fill-4 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-4 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-4 {
  -webkit-animation: animate-svg-fill-4 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8300000000000001s both;
          animation: animate-svg-fill-4 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8300000000000001s both;
}

@-webkit-keyframes animate-svg-fill-5 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-5 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-5 {
  -webkit-animation: animate-svg-fill-5 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8400000000000001s both;
          animation: animate-svg-fill-5 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8400000000000001s both;
}

@-webkit-keyframes animate-svg-fill-6 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-6 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-6 {
  -webkit-animation: animate-svg-fill-6 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8500000000000001s both;
          animation: animate-svg-fill-6 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8500000000000001s both;
}

@-webkit-keyframes animate-svg-fill-7 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-7 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-7 {
  -webkit-animation: animate-svg-fill-7 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8600000000000001s both;
          animation: animate-svg-fill-7 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8600000000000001s both;
}

@-webkit-keyframes animate-svg-fill-8 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-8 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-8 {
  -webkit-animation: animate-svg-fill-8 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8700000000000001s both;
          animation: animate-svg-fill-8 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8700000000000001s both;
}

@-webkit-keyframes animate-svg-fill-9 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-9 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-9 {
  -webkit-animation: animate-svg-fill-9 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.88s both;
          animation: animate-svg-fill-9 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.88s both;
}

@-webkit-keyframes animate-svg-fill-10 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-10 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-10 {
  -webkit-animation: animate-svg-fill-10 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.89s both;
          animation: animate-svg-fill-10 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.89s both;
}

@-webkit-keyframes animate-svg-fill-11 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-11 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-11 {
  -webkit-animation: animate-svg-fill-11 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9s both;
          animation: animate-svg-fill-11 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9s both;
}

@-webkit-keyframes animate-svg-fill-12 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-12 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-12 {
  -webkit-animation: animate-svg-fill-12 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.91s both;
          animation: animate-svg-fill-12 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.91s both;
}

@-webkit-keyframes animate-svg-fill-13 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-13 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-13 {
  -webkit-animation: animate-svg-fill-13 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.92s both;
          animation: animate-svg-fill-13 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.92s both;
}

@-webkit-keyframes animate-svg-fill-14 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-14 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-14 {
  -webkit-animation: animate-svg-fill-14 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.93s both;
          animation: animate-svg-fill-14 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.93s both;
}

@-webkit-keyframes animate-svg-fill-15 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-15 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-15 {
  -webkit-animation: animate-svg-fill-15 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9400000000000001s both;
          animation: animate-svg-fill-15 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9400000000000001s both;
}

@-webkit-keyframes animate-svg-fill-16 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-16 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-16 {
  -webkit-animation: animate-svg-fill-16 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9500000000000001s both;
          animation: animate-svg-fill-16 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9500000000000001s both;
}

@-webkit-keyframes animate-svg-fill-17 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-17 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-17 {
  -webkit-animation: animate-svg-fill-17 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9600000000000001s both;
          animation: animate-svg-fill-17 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9600000000000001s both;
}

@-webkit-keyframes animate-svg-fill-18 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-18 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-18 {
  -webkit-animation: animate-svg-fill-18 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9700000000000001s both;
          animation: animate-svg-fill-18 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9700000000000001s both;
}

@-webkit-keyframes animate-svg-fill-19 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-19 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-19 {
  -webkit-animation: animate-svg-fill-19 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.98s both;
          animation: animate-svg-fill-19 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.98s both;
}

@-webkit-keyframes animate-svg-fill-20 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-20 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-20 {
  -webkit-animation: animate-svg-fill-20 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.99s both;
          animation: animate-svg-fill-20 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.99s both;
}

@-webkit-keyframes animate-svg-fill-21 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-21 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-21 {
  -webkit-animation: animate-svg-fill-21 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1s both;
          animation: animate-svg-fill-21 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1s both;
}

@-webkit-keyframes animate-svg-fill-22 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-22 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-22 {
  -webkit-animation: animate-svg-fill-22 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.01s both;
          animation: animate-svg-fill-22 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.01s both;
}

@-webkit-keyframes animate-svg-fill-23 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-23 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-23 {
  -webkit-animation: animate-svg-fill-23 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.02s both;
          animation: animate-svg-fill-23 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.02s both;
}

@-webkit-keyframes animate-svg-fill-24 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-24 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-24 {
  -webkit-animation: animate-svg-fill-24 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.03s both;
          animation: animate-svg-fill-24 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.03s both;
}

@-webkit-keyframes animate-svg-fill-25 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-25 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-25 {
  -webkit-animation: animate-svg-fill-25 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.04s both;
          animation: animate-svg-fill-25 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.04s both;
}

@-webkit-keyframes animate-svg-fill-26 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-26 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-26 {
  -webkit-animation: animate-svg-fill-26 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.05s both;
          animation: animate-svg-fill-26 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.05s both;
}

@-webkit-keyframes animate-svg-fill-27 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-27 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-27 {
  -webkit-animation: animate-svg-fill-27 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.06s both;
          animation: animate-svg-fill-27 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.06s both;
}

@-webkit-keyframes animate-svg-fill-28 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-28 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-28 {
  -webkit-animation: animate-svg-fill-28 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.07s both;
          animation: animate-svg-fill-28 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.07s both;
}

@-webkit-keyframes animate-svg-fill-29 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-29 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-29 {
  -webkit-animation: animate-svg-fill-29 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.08s both;
          animation: animate-svg-fill-29 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.08s both;
}

@-webkit-keyframes animate-svg-fill-30 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-30 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-30 {
  -webkit-animation: animate-svg-fill-30 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.09s both;
          animation: animate-svg-fill-30 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.09s both;
}

@-webkit-keyframes animate-svg-fill-31 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-31 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-31 {
  -webkit-animation: animate-svg-fill-31 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.1s both;
          animation: animate-svg-fill-31 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.1s both;
}

@-webkit-keyframes animate-svg-fill-32 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-32 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-32 {
  -webkit-animation: animate-svg-fill-32 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.11s both;
          animation: animate-svg-fill-32 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.11s both;
}

@-webkit-keyframes animate-svg-fill-33 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-33 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-33 {
  -webkit-animation: animate-svg-fill-33 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.12s both;
          animation: animate-svg-fill-33 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.12s both;
}

@-webkit-keyframes animate-svg-fill-34 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-34 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-34 {
  -webkit-animation: animate-svg-fill-34 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.1300000000000001s both;
          animation: animate-svg-fill-34 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.1300000000000001s both;
}

@-webkit-keyframes animate-svg-fill-35 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-35 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-35 {
  -webkit-animation: animate-svg-fill-35 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.1400000000000001s both;
          animation: animate-svg-fill-35 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.1400000000000001s both;
}

@-webkit-keyframes animate-svg-fill-36 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-36 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-36 {
  -webkit-animation: animate-svg-fill-36 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.1500000000000001s both;
          animation: animate-svg-fill-36 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.1500000000000001s both;
}

@-webkit-keyframes animate-svg-fill-37 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-37 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-37 {
  -webkit-animation: animate-svg-fill-37 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.1600000000000001s both;
          animation: animate-svg-fill-37 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.1600000000000001s both;
}

@-webkit-keyframes animate-svg-fill-38 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-38 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-38 {
  -webkit-animation: animate-svg-fill-38 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.17s both;
          animation: animate-svg-fill-38 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.17s both;
}

@-webkit-keyframes animate-svg-fill-39 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-39 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-39 {
  -webkit-animation: animate-svg-fill-39 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.1800000000000002s both;
          animation: animate-svg-fill-39 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.1800000000000002s both;
}

@-webkit-keyframes animate-svg-fill-40 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-40 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-40 {
  -webkit-animation: animate-svg-fill-40 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.19s both;
          animation: animate-svg-fill-40 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.19s both;
}

@-webkit-keyframes animate-svg-fill-41 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-41 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-41 {
  -webkit-animation: animate-svg-fill-41 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.2000000000000002s both;
          animation: animate-svg-fill-41 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.2000000000000002s both;
}

@-webkit-keyframes animate-svg-fill-42 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-42 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-42 {
  -webkit-animation: animate-svg-fill-42 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.21s both;
          animation: animate-svg-fill-42 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.21s both;
}

@-webkit-keyframes animate-svg-fill-43 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-43 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-43 {
  -webkit-animation: animate-svg-fill-43 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.22s both;
          animation: animate-svg-fill-43 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.22s both;
}

@-webkit-keyframes animate-svg-fill-44 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-44 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-44 {
  -webkit-animation: animate-svg-fill-44 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.23s both;
          animation: animate-svg-fill-44 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.23s both;
}

@-webkit-keyframes animate-svg-fill-45 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-45 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-45 {
  -webkit-animation: animate-svg-fill-45 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.24s both;
          animation: animate-svg-fill-45 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.24s both;
}

@-webkit-keyframes animate-svg-fill-46 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-46 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-46 {
  -webkit-animation: animate-svg-fill-46 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.25s both;
          animation: animate-svg-fill-46 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.25s both;
}

@-webkit-keyframes animate-svg-fill-47 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-47 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-47 {
  -webkit-animation: animate-svg-fill-47 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.26s both;
          animation: animate-svg-fill-47 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.26s both;
}

@-webkit-keyframes animate-svg-fill-48 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-48 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-48 {
  -webkit-animation: animate-svg-fill-48 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.27s both;
          animation: animate-svg-fill-48 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.27s both;
}

@-webkit-keyframes animate-svg-fill-49 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-49 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-49 {
  -webkit-animation: animate-svg-fill-49 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.28s both;
          animation: animate-svg-fill-49 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.28s both;
}

@-webkit-keyframes animate-svg-fill-50 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-50 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-50 {
  -webkit-animation: animate-svg-fill-50 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.29s both;
          animation: animate-svg-fill-50 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.29s both;
}

@-webkit-keyframes animate-svg-fill-51 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-51 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-51 {
  -webkit-animation: animate-svg-fill-51 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.3s both;
          animation: animate-svg-fill-51 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.3s both;
}

@-webkit-keyframes animate-svg-fill-52 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-52 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-52 {
  -webkit-animation: animate-svg-fill-52 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.31s both;
          animation: animate-svg-fill-52 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.31s both;
}

@-webkit-keyframes animate-svg-fill-53 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-53 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-53 {
  -webkit-animation: animate-svg-fill-53 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.32s both;
          animation: animate-svg-fill-53 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.32s both;
}

@-webkit-keyframes animate-svg-fill-54 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-54 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-54 {
  -webkit-animation: animate-svg-fill-54 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.33s both;
          animation: animate-svg-fill-54 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.33s both;
}

@-webkit-keyframes animate-svg-fill-55 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-55 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-55 {
  -webkit-animation: animate-svg-fill-55 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.34s both;
          animation: animate-svg-fill-55 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.34s both;
}

@-webkit-keyframes animate-svg-fill-56 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-56 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-56 {
  -webkit-animation: animate-svg-fill-56 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.35s both;
          animation: animate-svg-fill-56 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.35s both;
}

@-webkit-keyframes animate-svg-fill-57 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-57 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-57 {
  -webkit-animation: animate-svg-fill-57 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.36s both;
          animation: animate-svg-fill-57 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.36s both;
}

@-webkit-keyframes animate-svg-fill-58 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-58 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-58 {
  -webkit-animation: animate-svg-fill-58 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.37s both;
          animation: animate-svg-fill-58 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.37s both;
}

@-webkit-keyframes animate-svg-fill-59 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-59 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-59 {
  -webkit-animation: animate-svg-fill-59 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.38s both;
          animation: animate-svg-fill-59 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.38s both;
}

@-webkit-keyframes animate-svg-fill-60 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-60 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-60 {
  -webkit-animation: animate-svg-fill-60 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.3900000000000001s both;
          animation: animate-svg-fill-60 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.3900000000000001s both;
}

@-webkit-keyframes animate-svg-fill-61 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-61 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-61 {
  -webkit-animation: animate-svg-fill-61 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.4s both;
          animation: animate-svg-fill-61 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.4s both;
}

@-webkit-keyframes animate-svg-fill-62 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-62 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-62 {
  -webkit-animation: animate-svg-fill-62 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.4100000000000001s both;
          animation: animate-svg-fill-62 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.4100000000000001s both;
}

@-webkit-keyframes animate-svg-fill-63 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-63 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-63 {
  -webkit-animation: animate-svg-fill-63 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.42s both;
          animation: animate-svg-fill-63 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.42s both;
}

@-webkit-keyframes animate-svg-fill-64 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

@keyframes animate-svg-fill-64 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(107, 162, 46);
  }
}

.svg-elem-64 {
  -webkit-animation: animate-svg-fill-64 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.4300000000000002s both;
          animation: animate-svg-fill-64 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.4300000000000002s both;
}

@-webkit-keyframes animate-svg-fill-65 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(239, 156, 16);
  }
}

@keyframes animate-svg-fill-65 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(239, 156, 16);
  }
}

.svg-elem-65 {
  -webkit-animation: animate-svg-fill-65 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.44s both;
          animation: animate-svg-fill-65 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.44s both;
}

@-webkit-keyframes animate-svg-fill-66 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(239, 156, 16);
  }
}

@keyframes animate-svg-fill-66 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(239, 156, 16);
  }
}

.svg-elem-66 {
  -webkit-animation: animate-svg-fill-66 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.4500000000000002s both;
          animation: animate-svg-fill-66 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.4500000000000002s both;
}

@-webkit-keyframes animate-svg-fill-67 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(239, 156, 16);
  }
}

@keyframes animate-svg-fill-67 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(239, 156, 16);
  }
}

.svg-elem-67 {
  -webkit-animation: animate-svg-fill-67 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.46s both;
          animation: animate-svg-fill-67 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.46s both;
}

@-webkit-keyframes animate-svg-fill-68 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(239, 156, 16);
  }
}

@keyframes animate-svg-fill-68 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(239, 156, 16);
  }
}

.svg-elem-68 {
  -webkit-animation: animate-svg-fill-68 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.4700000000000002s both;
          animation: animate-svg-fill-68 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.4700000000000002s both;
}

@-webkit-keyframes animate-svg-fill-69 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-69 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-69 {
  -webkit-animation: animate-svg-fill-69 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.48s both;
          animation: animate-svg-fill-69 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.48s both;
}

@-webkit-keyframes animate-svg-fill-70 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-70 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-70 {
  -webkit-animation: animate-svg-fill-70 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.4900000000000002s both;
          animation: animate-svg-fill-70 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.4900000000000002s both;
}

@-webkit-keyframes animate-svg-fill-71 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-71 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-71 {
  -webkit-animation: animate-svg-fill-71 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.5s both;
          animation: animate-svg-fill-71 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.5s both;
}

@-webkit-keyframes animate-svg-fill-72 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-72 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-72 {
  -webkit-animation: animate-svg-fill-72 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.51s both;
          animation: animate-svg-fill-72 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.51s both;
}

@-webkit-keyframes animate-svg-fill-73 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-73 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-73 {
  -webkit-animation: animate-svg-fill-73 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.52s both;
          animation: animate-svg-fill-73 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.52s both;
}

@-webkit-keyframes animate-svg-fill-74 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-74 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-74 {
  -webkit-animation: animate-svg-fill-74 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.53s both;
          animation: animate-svg-fill-74 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.53s both;
}

@-webkit-keyframes animate-svg-fill-75 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-75 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-75 {
  -webkit-animation: animate-svg-fill-75 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.54s both;
          animation: animate-svg-fill-75 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.54s both;
}

@-webkit-keyframes animate-svg-fill-76 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(238, 144, 18);
  }
}

@keyframes animate-svg-fill-76 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(238, 144, 18);
  }
}

.svg-elem-76 {
  -webkit-animation: animate-svg-fill-76 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.55s both;
          animation: animate-svg-fill-76 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.55s both;
}

@-webkit-keyframes animate-svg-fill-77 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(238, 144, 18);
  }
}

@keyframes animate-svg-fill-77 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(238, 144, 18);
  }
}

.svg-elem-77 {
  -webkit-animation: animate-svg-fill-77 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.56s both;
          animation: animate-svg-fill-77 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.56s both;
}

@-webkit-keyframes animate-svg-fill-78 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(238, 144, 18);
  }
}

@keyframes animate-svg-fill-78 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(238, 144, 18);
  }
}

.svg-elem-78 {
  -webkit-animation: animate-svg-fill-78 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.57s both;
          animation: animate-svg-fill-78 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.57s both;
}

@-webkit-keyframes animate-svg-fill-79 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(238, 144, 18);
  }
}

@keyframes animate-svg-fill-79 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(238, 144, 18);
  }
}

.svg-elem-79 {
  -webkit-animation: animate-svg-fill-79 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.58s both;
          animation: animate-svg-fill-79 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.58s both;
}

@-webkit-keyframes animate-svg-fill-80 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(238, 144, 18);
  }
}

@keyframes animate-svg-fill-80 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(238, 144, 18);
  }
}

.svg-elem-80 {
  -webkit-animation: animate-svg-fill-80 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.59s both;
          animation: animate-svg-fill-80 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.59s both;
}

@-webkit-keyframes animate-svg-fill-81 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-81 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-81 {
  -webkit-animation: animate-svg-fill-81 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.6s both;
          animation: animate-svg-fill-81 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.6s both;
}

@-webkit-keyframes animate-svg-fill-82 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-82 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-82 {
  -webkit-animation: animate-svg-fill-82 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.61s both;
          animation: animate-svg-fill-82 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.61s both;
}

@-webkit-keyframes animate-svg-fill-83 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-83 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-83 {
  -webkit-animation: animate-svg-fill-83 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.62s both;
          animation: animate-svg-fill-83 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.62s both;
}

@-webkit-keyframes animate-svg-fill-84 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-84 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-84 {
  -webkit-animation: animate-svg-fill-84 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.6300000000000001s both;
          animation: animate-svg-fill-84 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.6300000000000001s both;
}

@-webkit-keyframes animate-svg-fill-85 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-85 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-85 {
  -webkit-animation: animate-svg-fill-85 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.6400000000000001s both;
          animation: animate-svg-fill-85 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.6400000000000001s both;
}

@-webkit-keyframes animate-svg-fill-86 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-86 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-86 {
  -webkit-animation: animate-svg-fill-86 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.65s both;
          animation: animate-svg-fill-86 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.65s both;
}

@-webkit-keyframes animate-svg-fill-87 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-87 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-87 {
  -webkit-animation: animate-svg-fill-87 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.6600000000000001s both;
          animation: animate-svg-fill-87 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.6600000000000001s both;
}

@-webkit-keyframes animate-svg-fill-88 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-88 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-88 {
  -webkit-animation: animate-svg-fill-88 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.67s both;
          animation: animate-svg-fill-88 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.67s both;
}

@-webkit-keyframes animate-svg-fill-89 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-89 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-89 {
  -webkit-animation: animate-svg-fill-89 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.6800000000000002s both;
          animation: animate-svg-fill-89 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.6800000000000002s both;
}

@-webkit-keyframes animate-svg-fill-90 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-90 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-90 {
  -webkit-animation: animate-svg-fill-90 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.69s both;
          animation: animate-svg-fill-90 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.69s both;
}

@-webkit-keyframes animate-svg-fill-91 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-91 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-91 {
  -webkit-animation: animate-svg-fill-91 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.7000000000000002s both;
          animation: animate-svg-fill-91 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.7000000000000002s both;
}

@-webkit-keyframes animate-svg-fill-92 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-92 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-92 {
  -webkit-animation: animate-svg-fill-92 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.71s both;
          animation: animate-svg-fill-92 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.71s both;
}

@-webkit-keyframes animate-svg-fill-93 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-93 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-93 {
  -webkit-animation: animate-svg-fill-93 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.7200000000000002s both;
          animation: animate-svg-fill-93 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.7200000000000002s both;
}

@-webkit-keyframes animate-svg-fill-94 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-94 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-94 {
  -webkit-animation: animate-svg-fill-94 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.73s both;
          animation: animate-svg-fill-94 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.73s both;
}

@-webkit-keyframes animate-svg-fill-95 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-95 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-95 {
  -webkit-animation: animate-svg-fill-95 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.7400000000000002s both;
          animation: animate-svg-fill-95 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.7400000000000002s both;
}

@-webkit-keyframes animate-svg-fill-96 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-96 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-96 {
  -webkit-animation: animate-svg-fill-96 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.75s both;
          animation: animate-svg-fill-96 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.75s both;
}

@-webkit-keyframes animate-svg-fill-97 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-97 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-97 {
  -webkit-animation: animate-svg-fill-97 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.76s both;
          animation: animate-svg-fill-97 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.76s both;
}

@-webkit-keyframes animate-svg-fill-98 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-98 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-98 {
  -webkit-animation: animate-svg-fill-98 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.77s both;
          animation: animate-svg-fill-98 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.77s both;
}

@-webkit-keyframes animate-svg-fill-99 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(118, 119, 121);
  }
}

@keyframes animate-svg-fill-99 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(118, 119, 121);
  }
}

.svg-elem-99 {
  -webkit-animation: animate-svg-fill-99 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.78s both;
          animation: animate-svg-fill-99 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.78s both;
}

@-webkit-keyframes animate-svg-fill-100 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(118, 119, 121);
  }
}

@keyframes animate-svg-fill-100 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(118, 119, 121);
  }
}

.svg-elem-100 {
  -webkit-animation: animate-svg-fill-100 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.79s both;
          animation: animate-svg-fill-100 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.79s both;
}

@-webkit-keyframes animate-svg-fill-101 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(118, 119, 121);
  }
}

@keyframes animate-svg-fill-101 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(118, 119, 121);
  }
}

.svg-elem-101 {
  -webkit-animation: animate-svg-fill-101 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.8s both;
          animation: animate-svg-fill-101 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.8s both;
}

@-webkit-keyframes animate-svg-fill-102 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(118, 119, 121);
  }
}

@keyframes animate-svg-fill-102 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(118, 119, 121);
  }
}

.svg-elem-102 {
  -webkit-animation: animate-svg-fill-102 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.81s both;
          animation: animate-svg-fill-102 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.81s both;
}

@-webkit-keyframes animate-svg-fill-103 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(118, 119, 121);
  }
}

@keyframes animate-svg-fill-103 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(118, 119, 121);
  }
}

.svg-elem-103 {
  -webkit-animation: animate-svg-fill-103 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.82s both;
          animation: animate-svg-fill-103 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.82s both;
}

@-webkit-keyframes animate-svg-fill-104 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(118, 119, 121);
  }
}

@keyframes animate-svg-fill-104 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(118, 119, 121);
  }
}

.svg-elem-104 {
  -webkit-animation: animate-svg-fill-104 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.83s both;
          animation: animate-svg-fill-104 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.83s both;
}

@-webkit-keyframes animate-svg-fill-105 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(118, 119, 121);
  }
}

@keyframes animate-svg-fill-105 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(118, 119, 121);
  }
}

.svg-elem-105 {
  -webkit-animation: animate-svg-fill-105 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.84s both;
          animation: animate-svg-fill-105 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.84s both;
}

@-webkit-keyframes animate-svg-fill-106 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(118, 119, 121);
  }
}

@keyframes animate-svg-fill-106 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(118, 119, 121);
  }
}

.svg-elem-106 {
  -webkit-animation: animate-svg-fill-106 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.85s both;
          animation: animate-svg-fill-106 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.85s both;
}

@-webkit-keyframes animate-svg-fill-107 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(118, 119, 121);
  }
}

@keyframes animate-svg-fill-107 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(118, 119, 121);
  }
}

.svg-elem-107 {
  -webkit-animation: animate-svg-fill-107 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.86s both;
          animation: animate-svg-fill-107 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.86s both;
}

@-webkit-keyframes animate-svg-fill-108 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(118, 119, 121);
  }
}

@keyframes animate-svg-fill-108 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(118, 119, 121);
  }
}

.svg-elem-108 {
  -webkit-animation: animate-svg-fill-108 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.87s both;
          animation: animate-svg-fill-108 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.87s both;
}

@-webkit-keyframes animate-svg-fill-109 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(118, 119, 121);
  }
}

@keyframes animate-svg-fill-109 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(118, 119, 121);
  }
}

.svg-elem-109 {
  -webkit-animation: animate-svg-fill-109 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.8800000000000001s both;
          animation: animate-svg-fill-109 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.8800000000000001s both;
}

@-webkit-keyframes animate-svg-fill-110 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(118, 119, 121);
  }
}

@keyframes animate-svg-fill-110 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(118, 119, 121);
  }
}

.svg-elem-110 {
  -webkit-animation: animate-svg-fill-110 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.8900000000000001s both;
          animation: animate-svg-fill-110 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.8900000000000001s both;
}

@-webkit-keyframes animate-svg-fill-111 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(118, 119, 121);
  }
}

@keyframes animate-svg-fill-111 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(118, 119, 121);
  }
}

.svg-elem-111 {
  -webkit-animation: animate-svg-fill-111 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.9000000000000001s both;
          animation: animate-svg-fill-111 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.9000000000000001s both;
}

@-webkit-keyframes animate-svg-fill-112 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(118, 119, 121);
  }
}

@keyframes animate-svg-fill-112 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(118, 119, 121);
  }
}

.svg-elem-112 {
  -webkit-animation: animate-svg-fill-112 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.9100000000000001s both;
          animation: animate-svg-fill-112 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.9100000000000001s both;
}

@-webkit-keyframes animate-svg-fill-113 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(118, 119, 121);
  }
}

@keyframes animate-svg-fill-113 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(118, 119, 121);
  }
}

.svg-elem-113 {
  -webkit-animation: animate-svg-fill-113 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.9200000000000002s both;
          animation: animate-svg-fill-113 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.9200000000000002s both;
}

@-webkit-keyframes animate-svg-fill-114 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(118, 119, 121);
  }
}

@keyframes animate-svg-fill-114 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(118, 119, 121);
  }
}

.svg-elem-114 {
  -webkit-animation: animate-svg-fill-114 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.9300000000000002s both;
          animation: animate-svg-fill-114 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.9300000000000002s both;
}

@-webkit-keyframes animate-svg-fill-115 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(118, 119, 121);
  }
}

@keyframes animate-svg-fill-115 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(118, 119, 121);
  }
}

.svg-elem-115 {
  -webkit-animation: animate-svg-fill-115 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.9400000000000002s both;
          animation: animate-svg-fill-115 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.9400000000000002s both;
}

@-webkit-keyframes animate-svg-fill-116 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(118, 119, 121);
  }
}

@keyframes animate-svg-fill-116 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(118, 119, 121);
  }
}

.svg-elem-116 {
  -webkit-animation: animate-svg-fill-116 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.9500000000000002s both;
          animation: animate-svg-fill-116 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.9500000000000002s both;
}

@-webkit-keyframes animate-svg-fill-117 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-117 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-117 {
  -webkit-animation: animate-svg-fill-117 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.96s both;
          animation: animate-svg-fill-117 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.96s both;
}

@-webkit-keyframes animate-svg-fill-118 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-118 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-118 {
  -webkit-animation: animate-svg-fill-118 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.97s both;
          animation: animate-svg-fill-118 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.97s both;
}

@-webkit-keyframes animate-svg-fill-119 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-119 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-119 {
  -webkit-animation: animate-svg-fill-119 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.98s both;
          animation: animate-svg-fill-119 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.98s both;
}

@-webkit-keyframes animate-svg-fill-120 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-120 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-120 {
  -webkit-animation: animate-svg-fill-120 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.99s both;
          animation: animate-svg-fill-120 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.99s both;
}

@-webkit-keyframes animate-svg-fill-121 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-121 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-121 {
  -webkit-animation: animate-svg-fill-121 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2s both;
          animation: animate-svg-fill-121 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2s both;
}

@-webkit-keyframes animate-svg-fill-122 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-122 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-122 {
  -webkit-animation: animate-svg-fill-122 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.01s both;
          animation: animate-svg-fill-122 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.01s both;
}

@-webkit-keyframes animate-svg-fill-123 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-123 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-123 {
  -webkit-animation: animate-svg-fill-123 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.02s both;
          animation: animate-svg-fill-123 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.02s both;
}

@-webkit-keyframes animate-svg-fill-124 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-124 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-124 {
  -webkit-animation: animate-svg-fill-124 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.0300000000000002s both;
          animation: animate-svg-fill-124 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.0300000000000002s both;
}

@-webkit-keyframes animate-svg-fill-125 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-125 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-125 {
  -webkit-animation: animate-svg-fill-125 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.04s both;
          animation: animate-svg-fill-125 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.04s both;
}

@-webkit-keyframes animate-svg-fill-126 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-126 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-126 {
  -webkit-animation: animate-svg-fill-126 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.05s both;
          animation: animate-svg-fill-126 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.05s both;
}

@-webkit-keyframes animate-svg-fill-127 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-127 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-127 {
  -webkit-animation: animate-svg-fill-127 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.06s both;
          animation: animate-svg-fill-127 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.06s both;
}

@-webkit-keyframes animate-svg-fill-128 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-128 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-128 {
  -webkit-animation: animate-svg-fill-128 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.0700000000000003s both;
          animation: animate-svg-fill-128 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.0700000000000003s both;
}

@-webkit-keyframes animate-svg-fill-129 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-129 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-129 {
  -webkit-animation: animate-svg-fill-129 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.08s both;
          animation: animate-svg-fill-129 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.08s both;
}

@-webkit-keyframes animate-svg-fill-130 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-130 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-130 {
  -webkit-animation: animate-svg-fill-130 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.09s both;
          animation: animate-svg-fill-130 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.09s both;
}

@-webkit-keyframes animate-svg-fill-131 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-131 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-131 {
  -webkit-animation: animate-svg-fill-131 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.1s both;
          animation: animate-svg-fill-131 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.1s both;
}

@-webkit-keyframes animate-svg-fill-132 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-132 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-132 {
  -webkit-animation: animate-svg-fill-132 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.1100000000000003s both;
          animation: animate-svg-fill-132 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.1100000000000003s both;
}

@-webkit-keyframes animate-svg-fill-133 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

@keyframes animate-svg-fill-133 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 255, 255);
  }
}

.svg-elem-133 {
  -webkit-animation: animate-svg-fill-133 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.12s both;
          animation: animate-svg-fill-133 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.12s both;
}

</style>

    <link rel="shortcut icon" href="images/fav.png?id=53f0845ec654c0ac95bc0f0ba23f04c0">
	<link rel="apple-touch-icon" sizes="180x180" href="images/fav.png?id=8a2adfd4c8c31b802bbbe337ecfef4b1">
	<link rel="icon" type="image/png" sizes="32x32" href="images/fav.png?id=b8a8646eebfb3684427575635d56c963">
	<link rel="icon" type="image/png" sizes="16x16" href="images/fav.png?id=afe60bb0cb505b71b65660947f236e73">


        				
	<title>Home | Midas Touch School</title>
	<meta name="description" content="Welcome to Midas Touch School, a dynamic independent day school nestled in the Coimbatore. Explore our unique offering today." />

	<meta property="fb:app_id" content="">
	<meta property="og:url" content="#" />
	<meta property="og:type" content="website" />
	<meta property="og:title" content="Home | Midas Touch School" />
	<meta property="og:image" content="" />
	<meta property="og:image:width" content="1200" />
	<meta property="og:image:height" content="630" />
	<meta property="og:description" content="Welcome to Midas Touch School, a dynamic independent day school nestled in the Coimbatore. Explore our unique offering today." />
	<meta property="og:site_name" content="Midas Touch School" />
	<meta property="og:locale" content="en_GB" />
	<meta property="og:locale:alternate" content="en_GB" />
	
	<meta name="twitter:card" content="summary_large_image" />
	<meta name="twitter:site" content="" />
	<meta name="twitter:url" content="#" />
	<meta name="twitter:title" content="Home | Midas Touch School" />
	<meta name="twitter:description" content="Welcome to Midas Touch School, a dynamic independent day school nestled in the Coimbatore. Explore our unique offering today." />
	<meta name="twitter:image" content="" />

	
	<link rel="home" href="#" />
	<link rel="canonical" href="#">
        <link href="cpresources/c6a50153/css/formie-theme.css?v=1733182920" rel="stylesheet">
	
    
  </head>